name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in my YouTube Channels's posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBhgeQ1GV4acZ61fB8YPlIQ,https://www.youtube.com/feeds/videos.xml?channel_id=UCRifM7l2KAL9Bedwm8Mdsgg,https://www.youtube.com/feeds/videos.xml?channel_id=UCVOd5Ua0xxoPfupKVb4BMVw,https://www.youtube.com/feeds/videos.xml?channel_id=UCD0iVhUXUSWJk0yu7fsRJ1Q"
          
          
